In [1]:
import numpy as np

In [4]:
a = np.array([[3, 1], [1,2]])
b = np.array([9, 8])
a

array([[3, 1],
       [1, 2]])

In [5]:
b

array([9, 8])

In [6]:
np.linalg.solve(a, b)

array([2., 3.])

In [13]:
x = np.arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [19]:
np.logspace(0,10, 25, base=np.e)

array([1.00000000e+00, 1.51689680e+00, 2.30097589e+00, 3.49034296e+00,
       5.29449005e+00, 8.03119500e+00, 1.21824940e+01, 1.84795861e+01,
       2.80316249e+01, 4.25210820e+01, 6.45000931e+01, 9.78399845e+01,
       1.48413159e+02, 2.25127446e+02, 3.41495101e+02, 5.18012825e+02,
       7.85771994e+02, 1.19193502e+03, 1.80804241e+03, 2.74261375e+03,
       4.16026201e+03, 6.31068811e+03, 9.57266257e+03, 1.45207412e+04,
       2.20264658e+04])

In [20]:
np.logspace(0,10, 25, base=3)

array([1.00000000e+00, 1.58052192e+00, 2.49804953e+00, 3.94822204e+00,
       6.24025147e+00, 9.86285422e+00, 1.55884573e+01, 2.46378984e+01,
       3.89407384e+01, 6.15466905e+01, 9.72758934e+01, 1.53746682e+02,
       2.43000000e+02, 3.84066826e+02, 6.07026037e+02, 9.59417955e+02,
       1.51638111e+03, 2.39667358e+03, 3.78799512e+03, 5.98700931e+03,
       9.46259943e+03, 1.49558458e+04, 2.36380421e+04, 3.73604436e+04,
       5.90490000e+04])

In [47]:
np.random.seed(10)
np.random.rand(5,5)

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096],
       [0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317]])

In [48]:
np.random.rand(5,5)

array([[0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895],
       [0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935],
       [0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715],
       [0.54758616, 0.819287  , 0.19894754, 0.8568503 , 0.35165264],
       [0.75464769, 0.29596171, 0.88393648, 0.32551164, 0.1650159 ]])

In [49]:
np.random.randn(3,3)

array([[-0.80459114, -0.21269764, -0.33914025],
       [ 0.31216994,  0.56515267, -0.14742026],
       [-0.02590534,  0.2890942 , -0.53987907]])

In [50]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [54]:
np.diag([1,2,3,4], k =2)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [57]:
b = np.array([i for i in range(5)])
b

array([0, 1, 2, 3, 4])

In [64]:
c=np.arange(5)
c

array([0, 1, 2, 3, 4])

In [63]:
d = np.array(range(5))
d

array([0, 1, 2, 3, 4])

In [66]:
row_mask = np.array([True, False, True, False, False])

d[row_mask]

array([0, 2])

In [67]:
row_mask1 = np.array([0,0,0,1,1], dtype = bool)
d[row_mask1]

array([3, 4])

In [68]:
x = np.arange(0,10,0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [71]:
mask = (5 < x) & ( x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [72]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [74]:
indeces = np.where(mask)
indeces

(array([11, 12, 13, 14], dtype=int32),)

In [75]:
x[indeces]

array([5.5, 6. , 6.5, 7. ])

In [78]:
a= np.array([[1,2,3,4], [5,6,7,8], [1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
np.diag(a)

array([1, 6, 3, 8])

In [80]:
np.diag(a, k=1)

array([2, 7, 4])

In [81]:
v2 = np.arange(-3,3)
v2

array([-3, -2, -1,  0,  1,  2])

In [82]:
row_index = [1,3,5]
v2[row_index]

array([-2,  0,  2])

In [84]:
v2.take(row_index)

array([-2,  0,  2])

In [85]:
which = [1, 0, 1, 0]
options = [[-2, -3, -4, -5], [6, 7, 8, 9]]
np.choose(which, options)

array([ 6, -3,  8, -5])